### ISSUE TITLE
About max() in tournament_selection function

### ISSUE THREAD

**Issue by ly15927086342** [michstrauch/CoMOLA#1]
Hello!
Recently, I'm learning the principle of CoMOLA, there is a question I don't understand as follows:
In tournament_selection function, we choose the maximum of tourn, what's the criterion of max()? according to candidate or fitness? And as to a multi objective problem, how to judge a better one?
Expected to your answer, thank you!

**Comment by michstrauch** [comment]
Hello.
max(tourn) will return the candidate with higher fitness. In NSGA-II, higher fitness means a better rank after non-dominated sorting. The principles of non-dominated sorting are briefly described here: http://oklahomaanalytics.com/data-science-techniques/nsga-ii-explained/
Hope this helps.
Cheers,
Michael

**Comment by ly15927086342** [comment]
Ok,thanks for your answer and the software.
Best wishes!



发自我的小米手机在 Michael Strauch <notifications@github.com>，2019年3月18日 下午8:28写道：Hello.
max(tourn) will return the candidate with higher fitness. In NSGA-II, higher fitness means a better rank after non-dominated sorting. The principles of non-dominated sorting are briefly described here: http://oklahomaanalytics.com/data-science-techniques/nsga-ii-explained/
Hope this helps.
Cheers,
Michael

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/michstrauch/CoMOLA","title":"michstrauch/CoMOLA","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/michstrauch/CoMOLA"}},"updates":{"snippets":[{"icon":"PERSON","message":"@michstrauch in #1: Hello.\r\nmax(tourn) will return the candidate with higher fitness. In NSGA-II, higher fitness means a better rank after non-dominated sorting. The principles of non-dominated sorting are briefly described here: http://oklahomaanalytics.com/data-science-techniques/nsga-ii-explained/\r\nHope this helps.\r\nCheers,\r\nMichael"}],"action":{"name":"View Issue","url":"https://github.com/michstrauch/CoMOLA/issues/1#issuecomment-473889629"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/michstrauch/CoMOLA/issues/1#issuecomment-473889629",
"url": "https://github.com/michstrauch/CoMOLA/issues/1#issuecomment-473889629",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
