### ISSUE TITLE
Excuse me, but where can I find the R package named 'SDMTooobj1'?

### ISSUE THREAD

**Issue by JOHNDST** [michstrauch/CoMOLA#3]
In the R file named 'CoMOLA_postprocessing.R', there is a package named 'SDMTooobj1' installed, but i can't find it on the internet. Would you please tell me where I can find the package? Thank you so much.

**Comment by michstrauch** [comment]
I just realized package 'SDMTooobj' is not necessary for running the script. However, I've noticed another mistake while reading the best solutions from the log file which is now solved. Please use the updated script. Sorry for my late response!

Best,
Michael
