### ISSUE TITLE
Patch ID Map Plausibility Error

### ISSUE THREAD

**Issue by SarahMikaeil** [michstrauch/CoMOLA#5]
Hey, 
the following two errors come up whenever I try to edit the input patch ID map:
(1) SystemError: Error: Some cells of the patch ID map break the plausibility rules.
(2) IndexError: index 0 is out of bounds for axis 0 with size 0
I revised the plausibility checks, yet couldn't find the error. 
Could u plz explain further what are the limitations of editing the patch ID map?

**Comment by michstrauch** [comment]
Hi,  
the fact that both errors occur is strange.  
(1) "SystemError: ... plausibility rules" usually comes with a further error message explaining which plausibility issue occured. Please check again your optimization log file. If you cannot find any other hint, upload your patch ID map, land-use map, and the transition matrix. I'll have a look at it.  
(2) "IndexError: index 0 ..." tells that your patch ID map does not contain consecutive (!) integer values, starting with value 1. Value 0 can be used to indicate patches with static land use.
