### ISSUE TITLE
Landuse map rewrite

### ISSUE THREAD

**Issue by SarahMikaeil** [michstrauch/CoMOLA#6]
Hey,
Concerning the input file of land_use.asc , It overwrites it self in the 'models' folder with each run. So, Do I have to manually edit the file back to the original input file values to guarantee that the algorithm runs with the same first genome each time?

**Comment by michstrauch** [comment]
No, the algorithm will always use the land_use.asc file from the 'input' folder to define the first genome. In the 'models' folders, the genome will be updated automatically for each model run, starting with the initial genome from land_use.asc but later writing other genomes representing different land use maps as inputs for the models.

**Comment by michstrauch** [comment]
So you do not have to touch the genome.csv in the models folder ;)
